# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f5e8caf2cbc09df19b3f988631b388a0515ea4b8d36eb41eb3d6b5c9b85f925b645763df9e356d9811a96bfd4a3365257b2195866578a6d4e858b5d051ddc534

test:
  secret_key_base: a8a856962836692240a0c7108aeb072ec70b3c5c27fa3c76783c396889194f3958c05ff78911cbe94998d6ffec0830484b2c7a102b59e6d9fac1299d68fccc2b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
